apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-backend
spec:
  selector:
    matchLabels:
      app: eshop-backend
  template:
    metadata:
      labels:
        app: eshop-backend
    spec:
      containers:
        - name: eshop-backend
          image: eshop-backend
          ports:
          - containerPort: 8090
          env:
            - name: URL_CARTSERVICE
              value: http://eshop-cartservice:8091
            - name: URL_PRODUCTSERVICE
              value: http://eshop-productservice:8092
            - name: NATS_SPRING_SERVER
              value: "nats://nats-cluster:4222"
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-backend
spec:
  type: ClusterIP
  selector:
    app: eshop-backend
  ports:
  - port: 8090