apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-cartservice
spec:
  selector:
    matchLabels:
      app: eshop-cartservice
  template:
    metadata:
      labels:
        app: eshop-cartservice
    spec:
      containers:
        - name: eshop-cartservice
          image: eshop-cartservice
          ports:
          - containerPort: 8091
          env:
            - name: SPRING_REDIS_HOST
              value: redis
            - name: NATS_SPRING_SERVER
              value: "nats://nats-cluster:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-cartservice
spec:
  type: ClusterIP
  selector:
    app: eshop-cartservice
  ports:
  - port: 8091