apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eshop-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: eshop-frontend
          servicePort: 8080
      - path: /api/(.*)
        backend:
          serviceName: eshop-backend
          servicePort: 8090