apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-recommendservice
spec:
  selector:
    matchLabels:
      app: eshop-recommendservice
  template:
    metadata:
      labels:
        app: eshop-recommendservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: eshop-recommendservice
        image: eshop-recommendservice
        ports:
        - containerPort: 8093
        env:
          - name: URL_PRODUCTSERVICE
            value: http://eshop-productservice:8092
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-recommendservice
spec:
  type: ClusterIP
  selector:
    app: eshop-recommendservice
  ports:
  - name: api
    port: 8093
    targetPort: 8093